# Generated by Django 3.2.15 on 2023-05-05 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Наименование')),
                ('place_id', models.CharField(max_length=50, verbose_name='Идентификатор места')),
                ('type', models.CharField(max_length=20, verbose_name='Тип')),
                ('geometry_type', models.CharField(max_length=20, verbose_name='Тип фигуры на карте')),
                ('longitude', models.FloatField(max_length=10, verbose_name='Долгота')),
                ('latitude', models.FloatField(max_length=10, verbose_name='Широта')),
                ('details_url', models.CharField(max_length=300, verbose_name='Путь до описания')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата обновления')),
            ],
        ),
    ]
