# Generated by Django 3.2.15 on 2023-05-11 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_auto_20230510_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='position',
            field=models.IntegerField(blank=True, null=True, verbose_name='Позиция картинки'),
        ),
    ]
